if (NOT PROJECT_CONFIG_USER_LOADED)
set (PROJECT_CONFIG_USER_LOADED ON)

#set (CMAKE_BUILD_TYPE Release)


set (LIBARIES_BASE_DIR /home/sam/lib)
set (WORKSPACE_BASE_DIR /home/sam/workspace)

set(CMAKE_INSTALL_PREFIX ${LIBARIES_BASE_DIR}/inVRs2)
set(BOOST_ROOT ${LIBARIES_BASE_DIR}/boost_1_45_0)
set(ENV{OSG_ROOT} ${LIBARIES_BASE_DIR}/OpenSceneGraph)
set(ENV{OSGPPU_DIR} ${LIBARIES_BASE_DIR}/osgPPU)
set(ENV{OSGWIDGETADDONS_DIR} ${LIBARIES_BASE_DIR}/osgWidgetAddons)
set(GLUT_ROOT ${LIBARIES_BASE_DIR}/GLUT)
set(OPENSG_ROOT ${LIBARIES_BASE_DIR}/OpenSG2)
set(OPENSGSUPPORT_ROOT ${LIBARIES_BASE_DIR}/OpenSG/support)


endif()